pipeline {

    agent any
    
    stages {
        stage('Dependencies') {
            steps {
                dir("client") {
                    sh 'npm install'
                }

                
            }
        }
        stage('Build') {
            steps {
                dir("client") {
                sh 'npm run-script build'
                }
            }
        }
        stage('Delivery') {
            steps {
                echo "Delivery"
            }
        }
        
    }
}
