pipeline {

    agent any
    
    stages {
        stage('Build') {
            steps {
                dir("crm") {
                    sh 'gradle clean build'
                }                
            }
        }
        stage('Delivery') {
            steps {
                echo "Delivery"
            }
        }
        
    }
}
