POST http://localhost:8080/customers/ HTTP/1.1
content-type: application/json

{
        "firstName": "Rook",
        "middleName": "Rahrah",
        "lastName": "Rookinski",
        "currentStreetAddress": "1234 Rook Dr",
        "currentAddressLine1": "abc",
        "currentAddressLine2": "def",
        "currentAddressCity": "Rookago",
        "currentAddressState": "RI",
        "currentAddresszip": "12345",
        "currentAddressAddedDate": "2020-06-23T18:25:43.511Z",
        "previousStreetAddress": "4321 Dr Rook",
        "previousAddressLine1": "cba",
        "previousAddressLine2": "fed",
        "previousAddressCity": "Ogakoor",
        "previousAddressState": "IR",
        "previousAddresszip": "54321",
        "previousAddressAddedDate": "2010-06-23T18:25:43.511Z",
        "serviceStartDate": "2000-06-23T18:25:43.511Z",
        "dateOfBirth": null,
        "email": "rook@rook.net",
        "customerPhone": "123456789",
        "preferredContact": "email",
        "secondaryCustomerContact": "mobile",
        "products": "home; auto; boat",
        "activeCustomer": true
}